#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at travis-ci.org
#
#-----------------------------------------------------------------------------

language: generic

sudo: false

dist: trusty

#-----------------------------------------------------------------------------

# Save common build configurations as shortcuts, so we can reference them later.
addons_shortcuts:
  addons_clang35: &clang35
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.5' ]
      packages: [ 'clang-3.5' ]
  addons_clang38: &clang38
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.8' ]
      packages: [ 'clang-3.8' ]
  addons_clang39: &clang39
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.9' ]
      packages: [ 'clang-3.9' ]
  addons_clang39: &clang40
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0' ]
      packages: [ 'clang-4.0' ]
  addons_clang39: &clang50
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0' ]
      packages: [ 'clang-5.0' ]
  addons_gcc48: &gcc48
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-4.8', 'gcc-4.8' ]
  addons_gcc49: &gcc49
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-4.9', 'gcc-4.9' ]
  addons_gcc5: &gcc5
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-5', 'gcc-5' ]
  addons_gcc6: &gcc6
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-6', 'gcc-6', 'doxygen', 'graphviz' ]

#-----------------------------------------------------------------------------

matrix:
  include:
    - os: linux
      compiler: "clang-3.5"
      env: CXX=clang++-3.5 BUILD_TYPE='Debug'
      addons: *clang35
    - os: linux
      compiler: "clang-3.8"
      env: CXX=clang++-3.8 BUILD_TYPE='Debug'
      addons: *clang38
    - os: linux
      compiler: "clang-3.9"
      env: CXX=clang++-3.9 BUILD_TYPE='Debug'
      addons: *clang39
    - os: linux
      compiler: "clang-4.0"
      env: CXX=clang++-4.0 BUILD_TYPE='Debug'
      addons: *clang40
    - os: linux
      compiler: "clang-5.0"
      env: CXX=clang++-5.0 BUILD_TYPE='Debug'
      addons: *clang50
    - os: linux
      compiler: "clang-5.0"
      env: CXX=clang++-5.0 BUILD_TYPE='Release'
      addons: *clang50
    - os: linux
      compiler: "clang-5.0"
      env: CXX=clang++-5.0 BUILD_TYPE='Debug' RUN_CLANG_TIDY=1
      addons: *clang50
    - os: linux
      compiler: "clang-5.0"
      env: CXX=clang++-5.0 BUILD_TYPE='Debug'
           CXXFLAGS="-fsanitize=address,undefined,integer -fno-sanitize-recover=all -fno-omit-frame-pointer"
           LDFLAGS="-fsanitize=address,undefined,integer"
      addons: *clang50
    - os: linux
      compiler: "gcc-4.8"
      env: CXX=g++-4.8 BUILD_TYPE='Debug'
      addons: *gcc48
    - os: linux
      compiler: "gcc-4.9"
      env: CXX=g++-4.9 CXXFLAGS="--coverage" LDFLAGS="--coverage" BUILD_TYPE='Debug' COVERAGE=gcov-4.9
      addons: *gcc49
      script:
        - mkdir build
        - cd build
        - cmake -LA .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
        - make VERBOSE=1
        - ctest
        - which ${COVERAGE}
        - curl -S -f https://codecov.io/bash -o codecov
        - chmod +x codecov
        - ${COVERAGE} -p $(find test -name 'test_*.o')
        - ./codecov -Z -c -X gcov -F unit_tests
        - ${COVERAGE} -p $(find test -name 'fixture_tests.cpp.o')
        - ./codecov -Z -c -X gcov -F fixture_tests
    - os: linux
      compiler: "gcc-5"
      env: CXX=g++-5 BUILD_TYPE='Debug' CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"
      addons: *gcc5
    - os: linux
      compiler: "gcc-5"
      env: CXX=g++-5 BUILD_TYPE='Debug' CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=1"
      addons: *gcc5
    - os: linux
      compiler: "gcc-6"
      env: CXX=g++-6 BUILD_TYPE='Debug' BUILD_DOC=1
      addons: *gcc6
    - os: linux
      compiler: "gcc-6"
      env: CXX=g++-6 BUILD_TYPE='Release'
      addons: *gcc6
    - os: linux
      compiler: "gcc-6"
      env: CXX=g++-6 BUILD_TYPE='Debug' PROTOZERO_DATA_VIEW=std::experimental::string_view
      addons: *gcc6
    - os: osx
      osx_image: xcode6
      compiler: clang
      env: BUILD_TYPE='Debug'
    - os: osx
      osx_image: xcode7
      compiler: clang
      env: BUILD_TYPE='Debug'
    - os: osx
      osx_image: xcode8
      compiler: clang
      env: BUILD_TYPE='Debug'
    - os: osx
      osx_image: xcode8
      compiler: clang
      env: BUILD_TYPE='Release'

#-----------------------------------------------------------------------------

install:
  - git submodule update --init
  - (cd ..; git clone --depth=1 https://github.com/mapbox/protozero)

script:
  - mkdir build
  - cd build
  - cmake -LA .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DPROTOZERO_DATA_VIEW=$PROTOZERO_DATA_VIEW
  - make VERBOSE=1
  - ctest --output-on-failure
  - if [ -n "${BUILD_DOC}" ]; then make doc; fi
  - if [ -n "${RUN_CLANG_TIDY}" ]; then make clang-tidy; fi

#-----------------------------------------------------------------------------
